"""Add status column to Order table

Revision ID: 674bb3a0240d
Revises: a7e8c4804931
Create Date: 2023-08-04 22:26:20.353130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674bb3a0240d'
down_revision = 'a7e8c4804931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
