"""Add promocode column to Cart

Revision ID: 9419f6c20e20
Revises: 674bb3a0240d
Create Date: 2023-08-13 13:25:41.936045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9419f6c20e20'
down_revision = '674bb3a0240d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promocode', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('promocode')

    # ### end Alembic commands ###
